This notebook reproduces examples in https://kanoki.org/2019/11/12/how-to-use-regex-in-pandas/
<p>Except we user data from 2021 instead on 2019</p>

In [1]:
import pandas as pd
# df = pd.read_csv('./world-happiness-report-2019.csv')
df = pd.read_csv('../input/world-happiness-report/world-happiness-report-2021.csv')

In [2]:
df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [3]:
import numpy as np
df['first_five_Letter']=df['Country name'].str.extract(r'(^w{5})')
df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_Letter
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,...,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,NaN
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,...,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,NaN
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,...,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,NaN
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,...,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,NaN
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,...,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,NaN

In [4]:
S=pd.Series(['Finland','Colombia','Florida','Japan','Puerto Rico','Russia','france'])
S[S.str.count(r'(^F.*)')==1]

0    Finland
2    Florida
dtype: object

In [5]:
# Total items starting with F
S.str.count(r'(^F.*)').sum()

2

In [6]:
df[df['Country name'].str.count('^[pP].*')>0]

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_Letter
40,Panama,Latin America and Caribbean,6.180,0.073,6.323,6.036,10.350,0.896,69.652,0.872,...,0.856,2.43,1.298,0.976,0.667,0.596,0.079,0.053,2.509,NaN
43,Poland,Central and Eastern Europe,6.166,0.040,6.245,6.087,10.382,0.898,69.702,0.841,...,0.735,2.43,1.309,0.982,0.668,0.558,0.080,0.130,2.438,NaN
57,Portugal,Western Europe,5.929,0.055,6.037,5.821,10.421,0.879,72.600,0.892,...,0.887,2.43,1.323,0.939,0.760,0.621,0.029,0.033,2.225,NaN
60,Philippines,Southeast Asia,5.880,0.052,5.982,5.778,9.076,0.830,62.000,0.917,...,0.742,2.43,0.853,0.828,0.426,0.651,0.125,0.126,2.872,NaN
62,Peru,Latin America and Caribbean,5.840,0.075,5.988,5.692,9.458,0.832,68.250,0.822,...,0.891,2.43,0.986,0.833,0.623,0.536,0.087,0.031,2.744,NaN
70,Paraguay,Latin America and Caribbean,5.653,0.092,5.832,5.473,9.448,0.893,65.900,0.876,...,0.882,2.43,0.983,0.970,0.549,0.602,0.206,0.037,2.306,NaN
104,Pakistan,South Asia,4.934,0.068,5.066,4.802,8.458,0.651,58.709,0.726,...,0.787,2.43,0.637,0.423,0.322,0.418,0.252,0.097,2.784,NaN
124,Palestinian Territories,Middle East and North Africa,4.517,0.067,4.649,4.384,8.485,0.826,62.250,0.653,...,0.821,2.43,0.646,0.819,0.434,0.330,0.082,0.075,2.131,NaN

In [7]:
df[df['Country name'].str.match('^[UC].*')== True]

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_Letter
13,Canada,North America and ANZ,7.103,0.042,7.185,7.021,10.776,0.926,73.800,0.915,...,0.415,2.43,1.447,1.044,0.798,0.648,0.246,0.335,2.585,NaN
15,Costa Rica,Latin America and Caribbean,7.069,0.056,7.179,6.960,9.880,0.891,71.400,0.934,...,0.809,2.43,1.134,0.966,0.722,0.673,0.105,0.083,3.387,NaN
16,United Kingdom,Western Europe,7.064,0.038,7.138,6.990,10.707,0.934,72.500,0.859,...,0.459,2.43,1.423,1.062,0.757,0.580,0.340,0.306,2.596,NaN
17,Czech Republic,Central and Eastern Europe,6.965,0.049,7.062,6.868,10.556,0.947,70.807,0.858,...,0.868,2.43,1.370,1.090,0.703,0.580,0.052,0.046,3.124,NaN
18,United States,North America and ANZ,6.951,0.049,7.047,6.856,11.023,0.920,68.200,0.837,...,0.698,2.43,1.533,1.030,0.621,0.554,0.252,0.154,2.807,NaN
24,United Arab Emirates,Middle East and North Africa,6.561,0.039,6.637,6.484,11.085,0.844,67.333,0.932,...,0.589,2.43,1.555,0.860,0.594,0.670,0.236,0.223,2.422,NaN
30,Uruguay,Latin America and Caribbean,6.431,0.046,6.521,6.341,9.966,0.925,69.100,0.896,...,0.590,2.43,1.164,1.042,0.649,0.625,0.128,0.223,2.600,NaN
38,Cyprus,Western Europe,6.223,0.049,6.319,6.128,10.576,0.802,73.898,0.763,...,0.844,2.43,1.377,0.765,0.801,0.464,0.178,0.061,2.578,NaN
41,Uzbekistan,Commonwealth of Independent States,6.179,0.068,6.312,6.045,8.836,0.918,65.255,0.970,...,0.515,2.43,0.769,1.027,0.528,0.716,0.391,0.271,2.477,NaN
42,Chile,Latin America and Caribbean,6.172,0.046,6.262,6.081,10.071,0.882,70.000,0.742,...,0.830,2.43,1.200,0.946,0.678,0.438,0.159,0.070,2.682,NaN
51,Colombia,Latin America and Caribbean,6.012,0.061,6.132,5.892,9.557,0.847,68.001,0.837,...,0.841,2.43,1.021,0.866,0.615,0.554,0.100,0.063,2.794,NaN
59,Croatia,Central and Eastern Europe,5.882,0.048,5.975,5.788,10.217,0.924,70.799,0.754,...,0.939,2.43,1.251,1.039,0.703,0.453,0.111,0.000,2.325,NaN
82,Congo (Brazzaville),Sub-Saharan Africa,5.342,0.097,5.533,5.151,8.117,0.636,58.221,0.695,...,0.745,2.43,0.518,0.392,0.307,0.381,0.144,0.124,3.476,NaN
83,China,East Asia,5.339,0.029,5.397,5.281,9.673,0.811,69.593,0.904,...,0.755,2.43,1.061,0.785,0.665,0.636,0.093,0.117,1.982,NaN
90,Cameroon,Sub-Saharan Africa,5.142,0.074,5.288,4.996,8.189,0.710,53.515,0.731,...,0.848,2.43,0.543,0.556,0.159,0.425,0.205,0.058,3.195,NaN
109,Ukraine,Commonwealth of Independent States,4.875,0.052,4.977,4.773,9.436,0.888,64.902,0.724,...,0.924,2.43,0.979,0.958,0.517,0.417,0.181,0.010,1.813,NaN
113,Cambodia,Southeast Asia,4.830,0.067,4.963,4.698,8.360,0.765,62.000,0.959,...,0.843,2.43,0.603,0.680,0.426,0.702,0.210,0.061,2.148,NaN
118,Uganda,Sub-Saharan Africa,4.636,0.073,4.780,4.493,7.677,0.781,56.101,0.709,...,0.855,2.43,0.364,0.718,0.240,0.398,0.267,0.054,2.596,NaN
127,Chad,Sub-Saharan Africa,4.355,0.094,4.540,4.171,7.364,0.619,48.478,0.579,...,0.807,2.43,0.255,0.353,0.000,0.240,0.215,0.084,3.209,NaN
130,Comoros,Sub-Saharan Africa,4.289,0.084,4.454,4.123,8.031,0.626,57.349,0.548,...,0.781,2.43,0.488,0.367,0.279,0.202,0.241,0.101,2.610,NaN

In [8]:
# Remove the dash(-) followed by number from all countries in the Series
S=pd.Series(['Finland-1','Colombia-2','Florida-3','Japan-4','Puerto Rico-5','Russia-6','france-7'])
S.replace('(-d)','',regex=True, inplace = True)

In [9]:
S

0        Finland-1
1       Colombia-2
2        Florida-3
3          Japan-4
4    Puerto Rico-5
5         Russia-6
6         france-7
dtype: object

In [10]:
S=pd.Series(['Finland','Colombia','Florida','Japan','Puerto Rico','Russia','france'])
[itm[0] for itm in S.str.findall('^[Ff].*') if len(itm)>0]

['Finland', 'Florida', 'france']

In [11]:
S=pd.Series(['Finland','Colombia','Florida','Japan','Puerto Rico','Russia','france'])
S.str.contains('^F.*')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool

In [12]:
df[df['Country name'].str.contains('^I.*')==True]

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_Letter
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,...,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,NaN
11,Israel,Middle East and North Africa,7.157,0.034,7.224,7.090,10.575,0.939,73.503,0.800,...,0.753,2.43,1.376,1.074,0.788,0.509,0.208,0.119,3.083,NaN
14,Ireland,Western Europe,7.085,0.040,7.164,7.006,11.342,0.947,72.400,0.879,...,0.363,2.43,1.644,1.092,0.753,0.606,0.238,0.367,2.384,NaN
27,Italy,Western Europe,6.483,0.045,6.572,6.395,10.623,0.880,73.800,0.693,...,0.866,2.43,1.393,0.940,0.798,0.379,0.133,0.047,2.794,NaN
81,Indonesia,Southeast Asia,5.345,0.056,5.454,5.235,9.365,0.811,62.236,0.873,...,0.867,2.43,0.954,0.786,0.433,0.598,0.541,0.046,1.987,NaN
84,Ivory Coast,Sub-Saharan Africa,5.306,0.078,5.460,5.152,8.551,0.644,50.114,0.741,...,0.794,2.43,0.669,0.409,0.052,0.438,0.177,0.092,3.469,NaN
110,Iraq,Middle East and North Africa,4.854,0.059,4.970,4.738,9.240,0.746,60.583,0.630,...,0.875,2.43,0.910,0.638,0.381,0.302,0.153,0.041,2.429,NaN
117,Iran,Middle East and North Africa,4.721,0.055,4.828,4.614,9.584,0.710,66.300,0.608,...,0.714,2.43,1.030,0.557,0.561,0.275,0.330,0.144,1.823,NaN
138,India,South Asia,3.819,0.026,3.869,3.769,8.755,0.603,60.633,0.893,...,0.774,2.43,0.741,0.316,0.383,0.622,0.246,0.106,1.405,NaN

In [13]:
s = pd.Series(["StatueofLiberty built-on 28-Oct-1886"])
s.str.split(r"s", n=-1,expand=True)

                                      0
0  StatueofLiberty built-on 28-Oct-1886

In [14]:
# rsplit does same from end of string